scrounger:
  container_name: scrounger
  restart: always
  build: scrounger
  ports:
    - 5000:5000
  volumes:
    - ./scrounger:/app
  links:
    - postgres:postgres
  environment:
    - VIRTUAL_HOST=scrounger.docker
    - RUN_SCHEDULER=False

data:
  container_name: data
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql

postgres:
  container_name: postgres
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - 5432:5432

overwatch:
  container_name: overwatch
  build: overwatch
  ports:
    - 3000
  environment:
    - VIRTUAL_HOST=overwatch.docker