scrounger:
  build: scrounger
  command: python -u app/scrounger.py
  ports:
    - "5000:5000"
  volumes:
    - ./scrounger:/app
  links:
    - postgres:postgres
  environment:
    - RUN_SCHEDULER=False

db:
  image: mongo:3.0.2

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
