scrounger:
  container_name: scrounger
  restart: always
  build: scrounger
  command: python -u app/scrounger.py
  ports:
    - "5000:5000"
  volumes:
    - ./scrounger:/app
  links:
    - postgres:postgres
  environment:
    - RUN_SCHEDULER=False

data:
  container_name: data
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql

postgres:
  container_name: postgres
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"